from __future__ import annotations

import pandas as pd

from research_config import OUTPUT_ROOT, REPORTS_DIR, RESIDUAL_TREE_OUTPUT_DIR, TYPOLOGY_OUTPUT_DIR, ensure_workspace_dirs, residual_formula
from research_utils import df_to_markdown_table


def build_cluster_tip_summary(bridge: pd.DataFrame) -> pd.DataFrame:
    summary = (
        bridge.groupby(["cluster_id", "cluster_name"], dropna=False)
        .agg(
            zone_count=("LocationID", "nunique"),
            pickup_mean_raw_tiprate=("pickup_raw_longrun_tip_rate", "mean"),
            pickup_mean_residualized_tiprate=("pickup_residualized_tip_rate", "mean"),
            dropoff_mean_raw_tiprate=("dropoff_raw_longrun_tip_rate", "mean"),
            dropoff_mean_residualized_tiprate=("dropoff_residualized_tip_rate", "mean"),
        )
        .reset_index()
        .sort_values("cluster_id")
    )
    return summary


def write_workflow_report() -> None:
    manifest = pd.read_csv(OUTPUT_ROOT / "source_manifest.csv")
    cluster_summary = pd.read_csv(TYPOLOGY_OUTPUT_DIR / "typology_cluster_summary.csv")
    diagnostics = pd.read_csv(TYPOLOGY_OUTPUT_DIR / "typology_diagnostics.csv")
    residual_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "residual_model_summary.csv")
    pickup_tree_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "pickup_tree_model_summary.csv")
    dropoff_tree_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "dropoff_tree_model_summary.csv")
    pickup_cluster_leaf = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "pickup_cluster_x_leaf.csv")
    dropoff_cluster_leaf = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "dropoff_cluster_x_leaf.csv")
    bridge = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "zone_typology_tree_bridge.csv")
    cluster_tip_summary = build_cluster_tip_summary(bridge)

    lines = [
        "# 0426 Taxi Zone Typology + Residualized Tiprate Workflow",
        "",
        "## 1. 研究目标",
        "本轮 0426 研究把问题分成两层：",
        "1. 用 `KMeans k=6 + airport special` 固定一个不看 tiprate 的空间 typology。",
        "2. 在控制月度和行程结构后，对 `pickup` / `dropoff` 分别构造 residualized tiprate，并用浅层 regression tree 做 rule segmentation。",
        "",
        "这意味着 typology 回答“区域本身分成哪些城市类型”，而 tree 回答“控制后还有哪些阈值规则会系统性抬高或压低 tiprate”。",
        "",
        "## 2. 运行顺序",
        "1. `build_source_manifest.py`",
        "2. `build_typology_0426.py`",
        "3. `build_residualized_tiprate.py`",
        "4. `build_tiprate_trees.py`",
        "5. `generate_0426_reports.py`",
        "",
        "## 3. 外部数据依赖",
        "0426 不复制数据，所有上游输入继续引用仓库现有 `dataset/`、`data script/parquet/`、`data script/spatial/`。下面是本轮实际追踪的 source manifest：",
        "",
        df_to_markdown_table(manifest[["source_id", "source_family", "file_name", "row_count", "purpose"]]),
        "",
        "## 4. Typology 方法",
        "### 4.1 冻结特征",
        "本轮 typology 只保留 12 个变量：",
        "- `acs_mean_travel_time_min`",
        "- `acs_median_household_income`",
        "- `acs_poverty_rate`",
        "- `acs_rent_burden_30plus_share`",
        "- `commonplace_count_per_sqmi`",
        "- `mta_nearest_cbd_complex_dist_ft`",
        "- `mta_station_density_sqmi`",
        "- `pluto_landuse_share_04_mixed_residential_commercial`",
        "- `pluto_landuse_share_06_industrial_manufacturing`",
        "- `pluto_landuse_share_09_open_space_recreation`",
        "- `pluto_office_area_share_of_bldg`",
        "- `pluto_units_res_per_acre`",
        "",
        "### 4.2 特殊区处理",
        "- `LocationID in {1, 132, 138}` 的 airport zones 不进入主聚类，单独标记为 `Airport special zone`。",
        "- 非 airport universe 预期为 257 个 zone。",
        "",
        "### 4.3 聚类口径",
        "- 非 airport 样本对 12 个特征先做 `1%/99% winsorize`，再做 `z-score`。",
        "- diagnostics 继续计算 `k=4..8` 和 `KMeans/Agglomerative`，但正式 typology 固定为 `KMeans(n_clusters=6, random_state=42, n_init=50)`。",
        "",
        "### 4.4 Typology 结果",
        df_to_markdown_table(cluster_summary),
        "",
        "### 4.5 聚类 QA",
        df_to_markdown_table(diagnostics),
        "",
        "## 5. Residualized tiprate 方法",
        "### 5.1 建模口径",
        f"- 统一 WLS 公式：`{residual_formula()}`",
        "- 因变量：`avg_tip_rate`",
        "- 权重：`valid_tip_rate_trip_count`",
        "- `pickup` 与 `dropoff` 分开拟合，不合并目标。",
        "- 月度残差生成后，再按 zone 用 `valid_tip_rate_trip_count` 加权聚合成长期结构性偏差。",
        "",
        "### 5.2 Residual 模型摘要",
        df_to_markdown_table(residual_summary),
        "",
        "## 6. Tree segmentation 方法",
        "- tree 只在非 airport zones 上训练。",
        "- 目标分别是 `pickup_residualized_tip_rate` 和 `dropoff_residualized_tip_rate`。",
        "- 训练特征仍是同一组 12 个 zone-level 特征。",
        "- tree 输入特征只做 `1%/99% winsorize`，不做 z-score，保证阈值可解释。",
        "- 超参数网格固定：`max_depth in {2,3,4}`，`min_samples_leaf in {10,15,20,25}`。",
        "- 只接受最终 leaf 数在 `5-7` 的树，再按 `5-fold CV R²` 选择最优模型。",
        "",
        "### 6.1 Pickup tree 选择结果",
        df_to_markdown_table(pickup_tree_summary),
        "",
        "### 6.2 Dropoff tree 选择结果",
        df_to_markdown_table(dropoff_tree_summary),
        "",
        "## 7. 主结论",
        "### 7.1 Typology 层结论",
        "Typology 层面，高 tiprate cluster 仍然集中在 `CBD-accessible business core` 和 `Dense mixed-use neighborhood`，而低 tiprate cluster 主要是 `Housing-pressure residential zone` 与 `Outer-borough residential zone`。",
        "",
        df_to_markdown_table(cluster_tip_summary),
        "",
        "### 7.2 Tree 层结论",
        "Tree 层面，模型不是在“重新定义空间类型”，而是在现有 typology 之上继续切出解释 residualized tiprate 的阈值规则。",
        "如果某个 cluster 内部被分到多个 leaf，说明同类空间结构内部仍然存在残余的 tiprate 分层。",
        "同时也要注意：在控制 month FE、borough/service zone、coverage 和 trip composition 之后，当前浅层树的 5-fold CV R² 已经明显下降，说明 residualized tiprate 的剩余空间信号比 raw long-run tiprate 弱得多。",
        "因此 0426 里的 tree 更适合被解释为“规则化分段与异质性探查工具”，而不是高精度预测器。",
        "",
        "#### Pickup cluster × leaf",
        df_to_markdown_table(pickup_cluster_leaf),
        "",
        "#### Dropoff cluster × leaf",
        df_to_markdown_table(dropoff_cluster_leaf),
        "",
        "## 8. 结果解读边界",
        "- Typology 是描述性的空间分型，不是因果识别。",
        "- Residualized tiprate 已经控制了一部分月度和 trip composition，但仍然不是严格因果效应。",
        "- Tree 的价值是提供阈值规则解释，不是追求黑箱预测极限。",
        "- `Great Kills Park` 这类 zone 如果没有足够 panel 观测，可能没有 residual target，但仍然可以基于静态特征被映射到某个 tree leaf。",
        "",
        "## 9. 关键图",
        "![Typology map](../outputs/figures/typology_map.png)",
        "",
        "![Pickup tree](../outputs/figures/pickup_tree.png)",
        "",
        "![Dropoff tree](../outputs/figures/dropoff_tree.png)",
    ]

    (REPORTS_DIR / "01_workflow_methodology_findings_zh.md").write_text("\n".join(lines), encoding="utf-8")


def write_workflow_report_en() -> None:
    manifest = pd.read_csv(OUTPUT_ROOT / "source_manifest.csv")
    cluster_summary = pd.read_csv(TYPOLOGY_OUTPUT_DIR / "typology_cluster_summary.csv")
    diagnostics = pd.read_csv(TYPOLOGY_OUTPUT_DIR / "typology_diagnostics.csv")
    residual_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "residual_model_summary.csv")
    pickup_tree_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "pickup_tree_model_summary.csv")
    dropoff_tree_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "dropoff_tree_model_summary.csv")
    pickup_cluster_leaf = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "pickup_cluster_x_leaf.csv")
    dropoff_cluster_leaf = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "dropoff_cluster_x_leaf.csv")
    bridge = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "zone_typology_tree_bridge.csv")
    cluster_tip_summary = build_cluster_tip_summary(bridge)

    lines = [
        "# 0426 Taxi Zone Typology + Residualized Tiprate Workflow",
        "",
        "## 1. Research objective",
        "The 0426 package separates the research problem into two layers:",
        "1. Build a spatial typology with `KMeans k=6 + airport special` without using tiprate in clustering.",
        "2. Construct residualized tiprate for `pickup` and `dropoff` separately after controlling for month and trip composition, then fit shallow regression trees for rule-based segmentation.",
        "",
        "The typology answers “what kinds of urban zones exist,” while the trees answer “what threshold rules still explain tiprate differences after controls.”",
        "",
        "## 2. Execution order",
        "1. `build_source_manifest.py`",
        "2. `build_typology_0426.py`",
        "3. `build_residualized_tiprate.py`",
        "4. `build_tiprate_trees.py`",
        "5. `generate_0426_reports.py`",
        "",
        "## 3. External data dependencies",
        "0426 does not copy data. It reads the existing analysis data from `dataset/`, `data script/parquet/`, and `data script/spatial/`. The tracked source manifest is:",
        "",
        df_to_markdown_table(manifest[["source_id", "source_family", "file_name", "row_count", "purpose"]]),
        "",
        "## 4. Typology methodology",
        "### 4.1 Frozen feature set",
        "The typology uses the following 12 features:",
        "- `acs_mean_travel_time_min`",
        "- `acs_median_household_income`",
        "- `acs_poverty_rate`",
        "- `acs_rent_burden_30plus_share`",
        "- `commonplace_count_per_sqmi`",
        "- `mta_nearest_cbd_complex_dist_ft`",
        "- `mta_station_density_sqmi`",
        "- `pluto_landuse_share_04_mixed_residential_commercial`",
        "- `pluto_landuse_share_06_industrial_manufacturing`",
        "- `pluto_landuse_share_09_open_space_recreation`",
        "- `pluto_office_area_share_of_bldg`",
        "- `pluto_units_res_per_acre`",
        "",
        "### 4.2 Special-zone handling",
        "- Airport zones with `LocationID in {1, 132, 138}` are excluded from the main clustering and grouped into `Airport special zone`.",
        "- The non-airport clustering universe is expected to contain 257 zones.",
        "",
        "### 4.3 Clustering rule",
        "- The 12 features are winsorized at `1%/99%` and standardized with `z-score` for non-airport zones.",
        "- Diagnostics are still computed for `k=4..8` and both `KMeans` / `Agglomerative`, but the official 0426 typology is fixed at `KMeans(n_clusters=6, random_state=42, n_init=50)`.",
        "",
        "### 4.4 Typology results",
        df_to_markdown_table(cluster_summary),
        "",
        "### 4.5 Clustering QA",
        df_to_markdown_table(diagnostics),
        "",
        "## 5. Residualized tiprate methodology",
        "### 5.1 Modeling rule",
        f"- Unified WLS formula: `{residual_formula()}`",
        "- Outcome: `avg_tip_rate`",
        "- Weight: `valid_tip_rate_trip_count`",
        "- `pickup` and `dropoff` are modeled separately.",
        "- Monthly residuals are aggregated back to zone level using `valid_tip_rate_trip_count` as the weight.",
        "",
        "### 5.2 Residual model summary",
        df_to_markdown_table(residual_summary),
        "",
        "## 6. Tree segmentation methodology",
        "- Trees are trained on non-airport zones only.",
        "- Targets are `pickup_residualized_tip_rate` and `dropoff_residualized_tip_rate` separately.",
        "- Predictors remain the same 12 zone-level features.",
        "- Tree inputs are winsorized but not z-scored so that thresholds remain interpretable.",
        "- Hyperparameter grid: `max_depth in {2,3,4}` and `min_samples_leaf in {10,15,20,25}`.",
        "- Only trees with `5-7` terminal leaves are eligible, and the final choice is based on `5-fold CV R²`.",
        "",
        "### 6.1 Pickup tree selection",
        df_to_markdown_table(pickup_tree_summary),
        "",
        "### 6.2 Dropoff tree selection",
        df_to_markdown_table(dropoff_tree_summary),
        "",
        "## 7. Main findings",
        "### 7.1 Typology-layer findings",
        "At the typology level, the highest raw tiprate clusters remain `CBD-accessible business core` and `Dense mixed-use neighborhood`, while the lowest clusters are mainly `Housing-pressure residential zone` and `Outer-borough residential zone`.",
        "",
        df_to_markdown_table(cluster_tip_summary),
        "",
        "### 7.2 Tree-layer findings",
        "The trees do not redefine spatial types. Instead, they split zones within and across typology classes using threshold rules that explain residualized tiprate differences after controls.",
        "If one cluster maps into multiple leaves, that indicates residual heterogeneity inside the same spatial type.",
        "It is also important that once month fixed effects, borough/service-zone structure, coverage, and trip composition are controlled, the shallow-tree 5-fold CV R² drops materially.",
        "That means the remaining spatial signal in residualized tiprate is much weaker than in raw long-run tiprate, so the 0426 trees should be read as rule-based heterogeneity probes rather than high-accuracy predictors.",
        "",
        "#### Pickup cluster × leaf",
        df_to_markdown_table(pickup_cluster_leaf),
        "",
        "#### Dropoff cluster × leaf",
        df_to_markdown_table(dropoff_cluster_leaf),
        "",
        "## 8. Interpretation boundaries",
        "- The typology is descriptive, not causal.",
        "- Residualized tiprate controls for time and trip composition, but it is still not a causal treatment effect.",
        "- The trees are intended for threshold-based interpretation rather than black-box prediction.",
        "- Zones such as `Great Kills Park` may lack enough model-ready panel observations for a residual target, but can still be assigned to a tree leaf using static features.",
        "",
        "## 9. Key figures",
        "![Typology map](../outputs/figures/typology_map.png)",
        "",
        "![Pickup tree](../outputs/figures/pickup_tree.png)",
        "",
        "![Dropoff tree](../outputs/figures/dropoff_tree.png)",
    ]

    (REPORTS_DIR / "01_workflow_methodology_findings_en.md").write_text("\n".join(lines), encoding="utf-8")


def write_data_integration_report() -> None:
    manifest = pd.read_csv(OUTPUT_ROOT / "source_manifest.csv")
    commonplace_audit = pd.read_csv(TYPOLOGY_OUTPUT_DIR / "commonplace_join_audit.csv")
    residual_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "residual_model_summary.csv")

    lines = [
        "# 0426 数据整合与空间处理专题报告",
        "",
        "## 1. 数据资产结构",
        "本轮研究依赖 5 组核心数据库，再加上 geometry / crosswalk / panel 结果表：",
        "1. Taxi zone-month outcome panel",
        "2. ACS contextual features",
        "3. PLUTO built-environment features",
        "4. MTA accessibility features",
        "5. CommonPlace point inventory",
        "",
        df_to_markdown_table(manifest[["source_id", "source_family", "file_name", "row_count", "path"]]),
        "",
        "## 2. 主键与空间层级",
        "- 最终研究主键是 `LocationID`（Taxi Zone）。",
        "- Taxi outcome 的动态层级是 `LocationID × year_month`。",
        "- ACS / PLUTO / MTA / CommonPlace 最终都要收敛到 zone-level 才能组合。",
        "- geometry 基底使用 strict Taxi Zone polygon。",
        "",
        "## 3. 5 个数据库如何 combine",
        "### 3.1 Taxi",
        "- Taxi 部分使用已经清洗好的 `pickup_zone_month_panel_cc_enriched.parquet` 与 `dropoff_zone_month_panel_cc_enriched.parquet`。",
        "- 研究窗口是 zone-month panel，结果变量是 `avg_tip_rate`。",
        "- 长期对照口径使用 `pickup_zone_longrun_summary_cc.parquet` 与 `dropoff_zone_longrun_summary_cc.parquet`。",
        "",
        "### 3.2 ACS",
        "- ACS 输入不是 trip-level，而是 zone-level contextual features。",
        "- 上游 `zone_features_acs.parquet` 已经基于 tract 到 NTA/CDTA 的 crosswalk 和 `covered_area_share` 做过加权整合。",
        "- 0426 直接消费其 zone-level 结果，不再重做 ACS 原表清洗。",
        "",
        "### 3.3 PLUTO",
        "- PLUTO 上游先在 tract 层聚合 parcel 指标，再通过 `taxi_zone_to_tract.parquet` 的 `covered_area_share` 投影到 zone。",
        "- 所以 `pluto_units_res_per_acre`、`pluto_office_area_share_of_bldg`、land-use share 等变量在 0426 中都被视为 zone-level 静态 built-environment 指标。",
        "",
        "### 3.4 MTA",
        "- 上游 `zone_features_mta.parquet` 基于 strict Taxi Zone polygon 直接完成点位分配。",
        "- stop / complex 数量变量来自 point-in-polygon。",
        "- 最近站点 / 最近 CBD complex 距离来自 zone representative point 到最近点位的最近邻距离。",
        "",
        "### 3.5 CommonPlace",
        "- CommonPlace 是本轮唯一重新从原始文件进入 0426 pipeline 的点级数据。",
        "- `the_geom` 先按 WKT 解析，再从 EPSG:4326 投影到 EPSG:2263，与 Taxi Zone geometry 对齐。",
        "- 主匹配规则是 `within` point-in-polygon；未命中的点再做一次 `intersects` rescue。",
        "- 不依赖本地 codebook，因此本轮只保留 density / entropy / dominance 类指标，而不做更细语义 share。",
        "",
        "### 3.6 CommonPlace join audit",
        df_to_markdown_table(commonplace_audit),
        "",
        "## 4. Polygon 与 CRS 处理",
        "- Taxi Zone geometry 是全流程的空间容器。",
        "- CommonPlace 原始坐标先标准化到 Taxi Zone 同一投影，再做空间连接，避免混用经纬度和本地投影距离。",
        "- MTA 最近邻距离解释依赖代表点而不是完整 polygon-to-point 最短边界距离，这一口径更稳定也更便于批量计算。",
        "",
        "## 5. Tract / Zone 聚合方式",
        "- tract 是 ACS / PLUTO 向 Taxi Zone 投影时的核心中介层。",
        "- `taxi_zone_to_tract.parquet` 中的 `covered_area_share` 是主权重。",
        "- 这意味着大 zone 会按与 tract 的真实覆盖比例吸收静态特征，而不是简单 one-to-one 映射。",
        "- 对于没有完整 tract 覆盖的 zone，会保留 `tract_coverage_share` 和 partial-coverage 标记，供 residual model 控制。",
        "",
        "## 6. 异常值与质量控制",
        "- Typology 和 tree 的静态特征都采用 `1%/99% winsorize`。",
        "- Typology 再额外做 `z-score`，因为它服务于 KMeans。",
        "- Tree 不做 z-score，保留原量纲阈值解释。",
        "- Airport zones 不进入主聚类，也不进入 tree 训练，只作为 `Airport special zone` 单列。",
        "- `is_partial_coverage_zone`、`is_water_park_special_proxy`、`is_source_missing_special_area` 在 residual model 中被显式控制。",
        "",
        "## 7. Model-ready 过滤",
        "- residualized tiprate 不是对所有 zone 一视同仁直接回归，而是先对 zone-month panel 做 model-ready 检查。",
        "- 某些 zone 可能在 long-run 表里存在，但在当前控制公式下没有足够可用观测，这时 residualized tiprate 会缺失。",
        "- 当前 residual 模型摘要如下：",
        "",
        df_to_markdown_table(residual_summary),
        "",
        "## 8. 为什么 0426 不复制数据",
        "- 本轮目标是把研究 workflow 和结果包收口，不是重新做一套数据仓库。",
        "- 保持数据外置可以避免把 15GB 级别的原始 taxi 清洗数据再次复制。",
        "- source manifest 已经足以让后续维护者知道 0426 实际依赖了哪些外部文件、这些文件在什么路径、行数和体量是多少。",
    ]

    (REPORTS_DIR / "02_data_integration_and_spatial_processing_zh.md").write_text("\n".join(lines), encoding="utf-8")


def write_data_integration_report_en() -> None:
    manifest = pd.read_csv(OUTPUT_ROOT / "source_manifest.csv")
    commonplace_audit = pd.read_csv(TYPOLOGY_OUTPUT_DIR / "commonplace_join_audit.csv")
    residual_summary = pd.read_csv(RESIDUAL_TREE_OUTPUT_DIR / "residual_model_summary.csv")

    lines = [
        "# 0426 Data Integration and Spatial Processing Report",
        "",
        "## 1. Data asset structure",
        "This study combines five core data families, plus geometry / crosswalk / panel outputs:",
        "1. Taxi zone-month outcome panel",
        "2. ACS contextual features",
        "3. PLUTO built-environment features",
        "4. MTA accessibility features",
        "5. CommonPlace point inventory",
        "",
        df_to_markdown_table(manifest[["source_id", "source_family", "file_name", "row_count", "path"]]),
        "",
        "## 2. Keys and spatial grain",
        "- The final research key is `LocationID` (Taxi Zone).",
        "- The dynamic taxi outcome grain is `LocationID × year_month`.",
        "- ACS / PLUTO / MTA / CommonPlace are all ultimately collapsed to zone level before they are combined.",
        "- Strict Taxi Zone polygons are the spatial container for the entire workflow.",
        "",
        "## 3. How the five databases are combined",
        "### 3.1 Taxi",
        "- Taxi outcomes come from the cleaned `pickup_zone_month_panel_cc_enriched.parquet` and `dropoff_zone_month_panel_cc_enriched.parquet` files.",
        "- The working outcome is `avg_tip_rate` at the zone-month level.",
        "- Long-run cross-zone comparisons use `pickup_zone_longrun_summary_cc.parquet` and `dropoff_zone_longrun_summary_cc.parquet`.",
        "",
        "### 3.2 ACS",
        "- ACS enters the workflow as zone-level contextual features rather than trip-level records.",
        "- Upstream `zone_features_acs.parquet` already aggregates NTA/CDTA features into Taxi Zones using tract-based `covered_area_share` weights.",
        "- 0426 consumes this zone-level output directly instead of repeating raw ACS ingestion.",
        "",
        "### 3.3 PLUTO",
        "- Upstream PLUTO processing first aggregates parcel attributes to tract level, then projects them to Taxi Zones using `taxi_zone_to_tract.parquet` and `covered_area_share`.",
        "- Variables such as `pluto_units_res_per_acre`, `pluto_office_area_share_of_bldg`, and land-use shares are therefore treated as static zone-level built-environment features in 0426.",
        "",
        "### 3.4 MTA",
        "- `zone_features_mta.parquet` is built directly from strict Taxi Zone polygons.",
        "- Stop / complex counts come from point-in-polygon assignment.",
        "- Distance variables come from nearest-neighbor calculations between zone representative points and station / complex points.",
        "",
        "### 3.5 CommonPlace",
        "- CommonPlace is the only component that re-enters the 0426 pipeline from a raw point-level file.",
        "- `the_geom` is parsed from WKT and reprojected from EPSG:4326 to EPSG:2263 so it aligns with Taxi Zone geometry.",
        "- Primary matching uses `within` point-in-polygon; unmatched points then go through an `intersects` rescue pass.",
        "- Because there is no local semantic codebook, 0426 keeps only density / entropy / dominance style metrics rather than detailed semantic category shares.",
        "",
        "### 3.6 CommonPlace join audit",
        df_to_markdown_table(commonplace_audit),
        "",
        "## 4. Polygon and CRS handling",
        "- Taxi Zone geometry is the master spatial layer.",
        "- CommonPlace raw coordinates are transformed into the same projected CRS before spatial joins, avoiding mixed distance logic between longitude-latitude and local projected units.",
        "- MTA distance features are based on representative points rather than full polygon-to-point minimum-boundary distance, which is more stable for batch processing.",
        "",
        "## 5. Tract / zone aggregation logic",
        "- Tracts are the intermediate layer for ACS and PLUTO projection into Taxi Zones.",
        "- The key aggregation weight is `covered_area_share` from `taxi_zone_to_tract.parquet`.",
        "- This means large or irregular zones inherit contextual features according to actual spatial overlap rather than one-to-one lookup.",
        "- For incomplete tract coverage, `tract_coverage_share` and partial-coverage flags are retained and later used as residual-model controls.",
        "",
        "## 6. Outliers and quality control",
        "- Static features used in typology and trees are winsorized at `1%/99%`.",
        "- Typology additionally applies `z-score` scaling because KMeans is scale-sensitive.",
        "- Trees do not apply z-scoring so the split thresholds remain on the raw feature scale.",
        "- Airport zones are excluded from the main clustering and tree training and handled separately as `Airport special zone`.",
        "- `is_partial_coverage_zone`, `is_water_park_special_proxy`, and `is_source_missing_special_area` are explicitly controlled in the residual model.",
        "",
        "## 7. Model-ready filtering",
        "- Residualized tiprate is not estimated from every panel row blindly; the zone-month panel first has to satisfy the full model-ready column set.",
        "- Some zones may appear in long-run summaries but still lack enough usable panel observations under the full residualization formula.",
        "- The current residual-model summary is:",
        "",
        df_to_markdown_table(residual_summary),
        "",
        "## 8. Why 0426 does not copy data",
        "- The purpose of 0426 is to package the workflow, code, and outputs cleanly, not to rebuild a second data warehouse.",
        "- Keeping source data external avoids copying the 15GB-scale upstream taxi inputs again.",
        "- The source manifest is enough to document exactly which external files 0426 depends on, where they live, how large they are, and how many rows they contain.",
    ]

    (REPORTS_DIR / "02_data_integration_and_spatial_processing_en.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ensure_workspace_dirs()
    write_workflow_report()
    write_workflow_report_en()
    write_data_integration_report()
    write_data_integration_report_en()
    print("Saved 0426 markdown reports.")


if __name__ == "__main__":
    main()
